spring:
  sql:
    init:
      platform: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/web_socket_test
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate